# Generated by Django 3.1.2 on 2020-11-16 18:41

from django.db import migrations, models
import pandjas.objects


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FrameTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('template', models.JSONField()),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, pandjas.objects.FrameDef),
        ),
    ]
