# Generated by Django 3.1.2 on 2021-04-05 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_models', '0003_auto_20210405_2347'),
        ('pandjas', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FrameTemplate',
        ),
    ]
