# Generated by Django 3.1.2 on 2020-11-18 23:05

from django.db import migrations, models
import django.db.models.deletion
import pandjas.objects


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pandjas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestFrameModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame_file', models.FileField(blank=True, upload_to='pandjas/')),
                ('name', models.CharField(max_length=255)),
                ('frame_template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pandjas.frametemplate')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, pandjas.objects.PdFrame),
        ),
    ]
