# Generated by Django 3.1.2 on 2021-01-04 14:17

from django.db import migrations, models
import django.db.models.deletion
import pandjas.objects
import timezone_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pandjas', '0001_initial'),
        ('test_models', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestIntervalModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame_file', models.FileField(blank=True, upload_to='pandjas/')),
                ('timezone', timezone_field.fields.TimeZoneField(default='US/Pacific')),
                ('period_str', models.CharField(max_length=12)),
                ('name', models.CharField(max_length=255)),
                ('frame_template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pandjas.frametemplate')),
            ],
            options={
                'abstract': False,
            },
            bases=(pandjas.objects.PdIntervalFrame, models.Model, pandjas.objects.PdFrame),
        ),
    ]
