# Generated by Django 3.1.2 on 2021-04-05 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_models', '0002_testintervalmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testframemodel',
            name='frame_template',
        ),
        migrations.RemoveField(
            model_name='testintervalmodel',
            name='frame_template',
        ),
    ]
